const { resolveSoa } = require("dns");
const express = require("express");
const { appendFile } = require("fs");
const { dirname } = require("path");
const server = express();
const PORT = process.env.PORT || 3000

//to serve static file, we still need to use our methods to determine what it is we want to do with said file once we've served it 
// server.use(express.static(__dirname + '/Scenarios/index.html'))
//really we want to sent a request (user generated by choice selection) to our db json api that will then take the response and serve back consequences

//eventually, we will then want to send a request (user generated by choice selection) to sends a response that wants to send another request to the api and will continue to do so until you've reached a score that is under a certain amount of points (recognize that this entire preocess is potentially a recursive situation)
server.get("/", (req,res) => {
  res.sendFile(__dirname + '/Scenarios/index.html');
})

server.listen(PORT, () =>{
  console.log("Listening on port ", PORT);
});